### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by yusufozcan** [yasirkula/UnityNativeShare#90]
I am having error while running the game in Android. It was working before with same emulator and same game. I don't know what caused this error.

```
2020/09/04 01:53:59.675 29045 29089 Error Unity AndroidJavaException: java.lang.ClassNotFoundException: com.yasirkula.unity.NativeShare
2020/09/04 01:53:59.675 29045 29089 Error Unity java.lang.ClassNotFoundException: com.yasirkula.unity.NativeShare
2020/09/04 01:53:59.675 29045 29089 Error Unity 	at java.lang.Class.classForName(Native Method)
2020/09/04 01:53:59.675 29045 29089 Error Unity 	at java.lang.Class.forName(Class.java:400)
2020/09/04 01:53:59.675 29045 29089 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2020/09/04 01:53:59.675 29045 29089 Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source)
2020/09/04 01:53:59.675 29045 29089 Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source)
2020/09/04 01:53:59.675 29045 29089 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:98)
2020/09/04 01:53:59.675 29045 29089 Error Unity 	at android.os.Looper.loop(Looper.java:154)
2020/09/04 01:53:59.675 29045 29089 Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
2020/09/04 01:53:59.675 29045 29089 Error Unity Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yasirkula.unity.NativeShare" on path: DexPathList[[zip file "/data/app/com.UTECHGames.BalloonPopPaint-2/base.apk"],nativeLibraryDirectories=[/data/app/com.UTECHGames.BalloonPopPaint-2/lib/arm, /data/app/com.UTECHGames.BalloonPopPaint-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /data/downloads, /data/priv-downloads]]
2020/09/04 01:53:59.675 29045 29089 Error Unity 	at dalvik.system.BaseDexClas

```

Unity Version: 2020.1.2f1

**Comment by yusufozcan** [comment]
I have found the solution in unity forum.
https://forum.unity.com/threads/native-share-for-android-ios-open-source.519865/page-3#post-3854629

If your project uses ProGuard, try adding the following line to ProGuard filters:
-keep class com.yasirkula.unity.* { *; }

If someone needs the Proguard file is under Assets/Plugins/Android but it must be enabled under PlayerSettings-> Publishing Settings->(Check) Custom Proguard File.
